### ISSUE TITLE
Task 2 : adding createToken functionality 

### ISSUE THREAD

**Issue by itoshi69sae** [opencodeiiita/AssetMart#13]
This issue focuses on implementing the `createToken` function to streamline the creation and listing process for NFTs on the marketplace.

---

### **Tasks:**  
1. Create the `createToken` function with the following inputs:  
   - An IPFS URL that contains the metadata.  
   - The listing price for the NFT.  
2. Assign a `_tokenId` to the newly created NFT.  
3. Save the relevant data to the marketplace contract by creating a separate function which is called by the 'createToken' function which stores it in the contract(this function takes in the tokenID and the price) along with some metadata like owner,seller,isListed etc.  
4. Emit a **Listing Success** event upon completion.  

---

### **Requirements:**  
- First copy the given contract in the Contracts folder
- Ensure the `_tokenId` is unique and properly tracked.    
- The function should handle edge cases such as invalid inputs or network errors gracefully.  
- the NFT should be transferred over to the contract for selling
- Emit the event for successful transfer. The frontend will parse this message and update the end user
---

### **Submission Guidelines:**  
1. Pull the latest changes before pushing to the repository.  
2. Create a folder of your Github-ID in the Task-2 folder and submit the file in it
3. Submit a pull request (PR) using the provided PR template.    

---

### **Resources:**  
- [[IPFS Documentation](https://docs.ipfs.tech/)](https://docs.ipfs.tech/)  
- [[Ethereum Smart Contracts - Best Practices](https://consensys.github.io/smart-contract-best-practices/)](https://consensys.github.io/smart-contract-best-practices/)  
- [[OpenZeppelin ERC721 Documentation](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721)](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721)  

Feel free to ask for support on Discord if needed. Happy coding! 🚀

**Comment by gopijha021** [comment]
Claim

**Comment by official-ashutosh** [comment]
claim

**Comment by itoshi69sae** [comment]
Thanks everyone for trying and participating in the task.
