### ISSUE TITLE
Task 3 : Initialize React Frontend Repository

### ISSUE THREAD

**Issue by itoshi69sae** [opencodeiiita/AssetMart#20]
This issue involves setting up a React frontend repository with the basic structure and required pages for the project. It includes creating four main pages and two reusable components. The **NFT Sell** page will include a form for uploading an image and its metadata.

---

### **Tasks:**  
1. Initialize a new React project .  
2. Create the following pages:  
   - **Marketplace**  
       - (no implementation needed)
   - **NFTSell**  
     - Design a form that includes fields for:  
       - Uploading an NFT image.  
       - Adding metadata such as name, description, and attributes.  
   - **NFTListing**  
       - (no implementation needed)
   - **Profile**
       -  (no implementation needed)
3. Create the following components(pages only):  
   - **Navbar**  
     - (no implementation needed)
     - Displays navigation links (no implementation needed).  
     - Placeholder logic for Ethereum wallet connection (no implementation needed).  
   - **NftTile**  
     - A reusable component to display individual NFTs(no implementation needed).  
4. Ensure proper folder structure for pages and components.  

---

### **Requirements:**  
- All pages should be functional with placeholder content .  
- The **NFT Sell** page must have a clean and user-friendly form layout.  
-  For uploading the file to IPFS requires use of pinata library which will be implemented later so just leave file uploading function with a dummy implementation
- Your focus should be on creating on the best Page ui for the NFTsell page as the follow up issue will be on implementing the ethers.js logic

---

### **Submission Guidelines:**  
1. Pull the latest changes before pushing to the repository.  
2. Submit a pull request (PR) using the provided PR template.  
3. Include screenshots of the application and the **NFT Sell** form in the PR description (Mandatory).  

---

### **Resources:**  
- [[React Documentation](https://reactjs.org/docs/getting-started.html)](https://reactjs.org/docs/getting-started.html)  
- [[React Router Documentation](https://reactrouter.com/)](https://reactrouter.com/)  
- [[Form Design Best Practices](https://uxdesign.cc/creating-effective-form-designs-76b4a2f3e5e2)](https://uxdesign.cc/creating-effective-form-designs-76b4a2f3e5e2)  

Feel free to reach out on Discord for any clarifications or assistance. 🚀  

---

Let me know if there are any other changes you’d like!

**Comment by official-ashutosh** [comment]
claim

**Comment by itoshi69sae** [comment]
Sorry @official-ashutosh you are not eligible for issue assignment. Please complete 2 or more of the claimed issues to claim this issue

**Comment by official-ashutosh** [comment]
claim

**Comment by itoshi69sae** [comment]
info

**Comment by itoshi69sae** [comment]
Congratulations @Darkknight0125
