### ISSUE TITLE
Task 5: Add `getMyNFTs` Function to AssetMart Contract

### ISSUE THREAD

**Issue by saeitoshi-10** [opencodeiiita/AssetMart#30]
**Description:**  
This issue involves implementing the `getMyNFTs` function in the **AssetMart** contract. The function will retrieve all the NFTs currently owned by the logged-in user that are still for sale. This functionality will be used to populate the **Profile** page.

---

### **Tasks:**  
1. Implement the `getMyNFTs` function with the following specifications:  
   - **Input:** None  
   - **Output:** A list of all NFTs:  
     - Currently marked as "active" (for sale).  
     - Owned by the currently logged-in user.  
2. Place the `getMyNFTs` function directly below the `getAllNFTs` function in the **AssetMart** contract.  

---

### **Requirements:**  
- The function should fetch all "active" NFTs from the marketplace and filter them by the owner address(msg.sender) of the logged-in user.  
- Metadata for each NFT should be properly included in the output.  
- Ensure the function adheres to the contract's architecture and coding standards.  
- Copy the given contract from the contracts and add the function in it
- For reference look at the getAllNFTs function in the contract

---

### **Submission Guidelines:**  
1. Pull the latest changes before pushing to the repository.  
2. Submit a pull request (PR) using the provided PR template.  
3. Create a folder of your Github ID and submit the modified Contract in it

---

### **Resources:**  
- [[Solidity Documentation](https://docs.soliditylang.org/)](https://docs.soliditylang.org/)  
- [[OpenZeppelin Contracts](https://docs.openzeppelin.com/contracts/)](https://docs.openzeppelin.com/contracts/)  
- [[Best Practices for NFT Marketplaces](https://consensys.github.io/smart-contract-best-practices/)](https://consensys.github.io/smart-contract-best-practices/)  

Feel free to ask for support or clarifications on Discord if needed. 🚀

**Comment by itoshi69sae** [comment]
keep in mind this function is to be directly called by the profile page to fetch your NFT and their metadata

**Comment by saeitoshi-10** [comment]
thanks for contributing to this issue
