### ISSUE TITLE
Task 8: Add Functions to Upload NFT Metadata to Piñata

### ISSUE THREAD

**Issue by saeitoshi-10** [opencodeiiita/AssetMart#40]
**Description:**  
This issue involves implementing two functions in a new file, `pinata.js`, located in the project’s home directory. These functions will facilitate uploading NFT image files and metadata to IPFS using Piñata's API.  

---

### **Tasks:**  
1. Create a new file named `pinata.js` in the project’s home directory.  
2. Implement the following functions:  
   - **`uploadFileToIPFS()`**:  
     - Uploads an NFT image file to IPFS.  
     - Returns an IPFS URL that can be queried to obtain the image.  
   - **`uploadJSONToIPFS(JSON)`**:  
     - Takes a JSON object as input.  
     - Uploads the JSON to IPFS and returns an IPFS URI for retrieving the metadata later.  

---

### **Requirements:**  
- Use the Piñata API for both functions.  
- Ensure the functions are modular and reusable.  
- Add placeholder comments for API key and secret configuration.  
- Include proper error handling for cases such as failed uploads or API errors.  

---

### **Submission Guidelines:**  
1. Pull the latest changes before pushing to the repository.  
2. Submit a pull request (PR) using the provided PR template.  
3. Include sample usage of the functions in the PR description or a separate test file.  

---

### **Resources:**  
- [[Piñata Documentation](https://docs.pinata.cloud/)](https://docs.pinata.cloud/)  
- [[Using IPFS for NFTs](https://nftschool.dev/concepts/ipfs-for-nfts/)](https://nftschool.dev/concepts/ipfs-for-nfts/)  
- [[Axios for API Requests](https://axios-http.com/docs/intro)](https://axios-http.com/docs/intro)  

Feel free to reach out on Discord if you have questions or need assistance. 🚀

**Comment by saeitoshi-10** [comment]
This is a fcfs task so claim it fast

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by saeitoshi-10** [comment]
@PriyamJChakrabarty sorry can't be assigned. resolve one or more issues to be eligible

**Comment by saeitoshi-10** [comment]
Congratulations @Darkknight0125 !!!

**Comment by saeitoshi-10** [comment]
@Darkknight0125 try to finish the task in 2-3 days to make up for lost  #grounds

**Comment by Darkknight0125** [comment]
@saeitoshi-10 Will try to finish asap 👍🏻. Positively by tomm morning
